### ISSUE TITLE
Nodes with the same ServiceID are overwritten in response

### ISSUE THREAD

**Issue by thunderer** [dcarbone/php-consul-api#13]
Hi, thanks for the excellent work on this client! I have a question though - I see that in `CatalogClient::service()` the results [are indexed](https://github.com/dcarbone/php-consul-api/blob/033983cea01d225fbb188765a1d146557209f6df/src/Catalog/CatalogClient.php#L175) by `ServiceID`. In our case we have several nodes under the same `ServiceID` which makes them invisible (only one record is returned).

Is that intentional? If not, is the removal of array index a sufficient fix for the issue? I'm happy to work on the PR if that's the case. Thanks!

**Comment by dcarbone** [comment]
Ah, it was intentional but clearly shortsighted on my part :)

You're welcome to make a PR and yes the fix would be to just turn it into a typical array.

**Comment by dcarbone** [comment]
Fixed in #14
