### ISSUE TITLE
KV\KVClient::cas destroys value and returns no success indication

### ISSUE THREAD

**Issue by adrmcintyre** [dcarbone/php-consul-api#15]
The ```KV\KVClient->cas``` method doesn't append ```$p->Value``` to the PUT Request, so the value in consul gets overwritten with null.

I also can't see an obvious way to determine if the PUT succeeded or failed due to cas mismatch, short of issuing a follow-up get request and checking to see if ModifyIndex has changed. Note that consul's http interface indicates success by setting the response body to "true" or "false".

The acquire and release methods may well have the same problem, though I'm not currently making use of them.

**Comment by dcarbone** [comment]
@adrmcintyre: Thanks for this!  It actually IS properly setting the CAS value, it just isn't parsing the response properly.  `deleteCAS` has a similar issue. 

I have addressed this issue in master, and will update the 0.6 release here shortly.

Sorry for the inconvenience!

**Comment by dcarbone** [comment]
@adrmcintyre: This is how it should be interacted with now:
```php
list($ok, $wm, $err) = $kvClient->cas($kv);
if (null !== $err) {
    // handle err
}
if (!$ok) {
    // update failed, cas out of date.
}
```

Let me know if you run into anything else.

**Comment by adrmcintyre** [comment]
Thanks for responding so quickly. The success value is now returned correctly, but it still looks like the following patch is needed to make sure the Value part of the KVPair is stored remotely, otherwise it gets clobbered and set to null:

```
     public function cas(KVPair $p, WriteOptions $options = null) {
-        $r = new Request('PUT', sprintf('v1/kv/%s', $p->Key), $this->config);
+        $r = new Request('PUT', sprintf('v1/kv/%s', $p->Key), $this->config, $p->Value);
```

**Comment by dcarbone** [comment]
Absolutely correct, that's what I get for not listening to myself and omitting assert call in the tests.

Should now be addressed properly.

**Comment by adrmcintyre** [comment]
Nice work - that's fixed it!
