### ISSUE TITLE
DCarbone\PHPConsulAPI\Request.  setWriteOptions may be not correct

### ISSUE THREAD

**Issue by leeyifei** [dcarbone/php-consul-api#19]
`if ('' !== $options->Token) {
            if ($this->config->TokenInHeader) {
                $this->Headers->set('X-Consul-Token', $options->Token);
            } else {
                $this->Headers->set('token', $options->Token);
            }
        }`

should be changed to 
`if ('' !== $options->Token) {
            if ($this->config->TokenInHeader) {
                $this->Headers->set('X-Consul-Token', $options->Token);
            } else {
                $this->Params->set('token', $options->Token);
            }
        }`

I found that I can not use another token while put kv in my project. please fix this bug~~ THX~~

**Comment by dcarbone** [comment]
@leeyifei: yep sorry about that, tag 0.6.4 addresses this.

**Comment by leeyifei** [comment]
got it, work, thx
