### ISSUE TITLE
guzzlehttp/psr7 2.0 support

### ISSUE THREAD

**Issue by stseira** [dcarbone/php-consul-api#23]
Hi,

Cause our project using php 8 and [guzzlehttp/psr7 2.0](https://github.com/guzzle/psr7/releases/tag/2.0.0), so when we install this package, there is some dependency issue.

<img width="1429" alt="Screen Shot 2021-10-04 at 13 24 06" src="https://user-images.githubusercontent.com/199357/135794538-9f61dd8b-07eb-47eb-943d-ebbb105e0790.png">

Plz consider this library support `guzzlehttp/psr7` 2.0.
Thanks.

**Comment by dcarbone** [comment]
@stseira: i've released v1.0.5 to address this.  Please let me know if you find anything else!

**Comment by yeonggwon-jeong** [comment]
Thanks! i've updated 1.0.5 and there is no problem.

**Comment by stseira** [comment]
Thanks. I've updated to v1.0.5 and checked the dependency issue solved.
