### ISSUE TITLE
Array to int conversion in failed 'require status' message

### ISSUE THREAD

**Issue by deanstalker** [dcarbone/php-consul-api#34]
https://github.com/dcarbone/php-consul-api/blob/master/src/AbstractClient.php#L235

I have noticed when an unexpected status code is returned, the error will not mention the allowed status code, instead it says ...

`<namespace redacted>\KVClient - Non-1 response seen.  Response code: 404.  Response: ` 

Expected behaviour is to return 

`jumbo\lotteries\core\config\consul\KVClient - Non-200 response seen.  Response code: 404.  Response: `

This is due to type casting the array `$allowed` to an int in the `sprintf` call.

**Comment by dcarbone** [comment]
Thanks for reporting this!  I've address this issue with #35 and released [v1.1.3](https://github.com/dcarbone/php-consul-api/releases/tag/v1.1.3)
