### ISSUE TITLE
There is a php8.2 compatibility issue

### ISSUE THREAD

**Issue by vssir** [dcarbone/php-consul-api#38]
File: src/Unmarshaller.php
8.2 The class dynamic attributes are deprecated. You can fix compatibility by doing this
Add:
`
    private $dynamicProperty = [];

    public function __set(string $name, mixed $value) {
        $this->dynamicProperty[$name] = $value;
    }

    public function __get(string $name){
        return $this->dynamicProperty[$name];
    }`

**Comment by dcarbone** [comment]
released v1.1.5 with fix.
