### ISSUE TITLE
Dev: no type specified errors

### ISSUE THREAD

**Issue by kai890707** [dcarbone/php-consul-api#41]
I'm getting the following error, which so far seems to be an error triggered by not specifying the type of error.

`PHP Deprecated:  Return type of DCarbone\PHPConsulAPI\FakeMap::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/dcarbone/php-consul-api/src/FakeMap.php on line 110
PHP Deprecated:  Return type of DCarbone\PHPConsulAPI\FakeMap::current() should either be compatible with Iterator::current(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/dcarbone/php-consul-api/src/FakeMap.php on line 66
PHP Deprecated:  Return type of DCarbone\PHPConsulAPI\FakeMap::key() should either be compatible with Iterator::key(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /app/vendor/dcarbone/php-consul-api/src/FakeMap.php on line 79`

Can I send a PR to solve this problem?

**Comment by dcarbone** [comment]
addressed with #42.  thanks!
