### ISSUE TITLE
Unable to install with composer

### ISSUE THREAD

**Issue by mariusmitrofan** [dcarbone/php-consul-api#7]
```
# composer require dcarbone/php-consul-api
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^0.4.5 for dcarbone/php-consul-api
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for dcarbone/php-consul-api ^0.4.5 -> satisfiable by dcarbone/php-consul-api[0.4.5].
    - dcarbone/php-consul-api 0.4.5 requires php-http/client-implementation @stable -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

I can't find the dependency either (`php-http/client-implementation`).

Is there something else I should install prior to this?

**Comment by dcarbone** [comment]
Right so `php-http/client-implementation` is an example of [dependency inversion](https://php-and-symfony.matthiasnoback.nl/2014/10/composer-provide-and-dependency-inversion/). 

It basically means that in your projects composer file you must include a package that says it provides `php-http/client-implementation`, it itself is not a package. 

To see a list of packages that provide this functionality, see [here](https://packagist.org/search/?q=php-http%2Fclient-implementation). 

Let me know if you have any other issues!

**Comment by dcarbone** [comment]
@mariusmitrofan: unless you have anymore questions I am going to close this issue.

**Comment by dcarbone** [comment]
Closing, but making a note on this potential barrier of entry.
