### ISSUE TITLE
Fatal error: Class 'DCarbone\PHPConsulAPI\Config' not found in

### ISSUE THREAD

**Issue by anissa747** [dcarbone/php-consul-api#9]
I don't find examples in internet on how to use this api.
So when I launch my script I have this error : "Fatal error: Class 'DCarbone\PHPConsulAPI\Config' not found in "
My script :

<?php 

/* Config */
$config = new \DCarbone\PHPConsulAPI\Config([ 
    'HttpClient' => $client, // REQUIRED Client conforming to GuzzleHttp\ClientInterface

    'Address' => 'consul.service.blabla.com:8500', // REQUIRED
    'Scheme' => 'http', // REQUIRED
    //'Datacenter' => '', // OPTIONAL
    //'HttpAuth' => 'user:pass', // OPTIONAL,
    'WaitTime' => 30, // OPTIONAL, not used yet
    //'Token' => 'auth token', // OPTIONAL
    'TokenInHeader' => true, // OPTIONAL
    'InsecureSkipVerify' => true, // OPTIONAL
]);

$consul = new \DCarbone\PHPConsulAPI\Consul($config);

$kv = $consul->KV;

list($kvp, $qm, $err) = $consul->KV->get('user/marky/cassandra/instance1/username');
if (null !== $err)
    die($err);

var_dump($qm, $kvp);
?>

Thank you !

**Comment by dcarbone** [comment]
Hey @anissa747, could you paste a bit more of your script in here please?  

From the outset it looks as though you aren't including the [Composer autoloader](https://getcomposer.org/doc/01-basic-usage.md#autoloading) before attempting to construct the client.  

The important line is:

```php
require __DIR__ . '/vendor/autoload.php';
```

The path must be modified to your specific implementation.

**Comment by anissa747** [comment]
Ok now I have these errors :
- "Notice: Undefined variable: client in" 
- "Catchable fatal error: Argument 1 passed to DCarbone\PHPConsulAPI\Config::setHttpClient() must be an instance of GuzzleHttp\ClientInterface, null given, called in C:\wamp64\www\Stage\php\Composer\vendor\dcarbone\php-consul-api\src\Config.php on line 95 and defined in C:\wamp64\www\Stage\php\Composer\vendor\dcarbone\php-consul-api\src\Config.php on line 283"

All my script:
`<?php 

require __DIR__ . '/Composer/vendor/autoload.php';

/* Config */
$config = new \DCarbone\PHPConsulAPI\Config([ 
    'HttpClient' => $client, // REQUIRED Client conforming to GuzzleHttp\ClientInterface

    'Address' => 'consul.service.blabla.com:8500', // REQUIRED
    'Scheme' => 'http', // REQUIRED
   // 'Datacenter' => ', // OPTIONAL
    //'HttpAuth' => 'user:pass', // OPTIONAL,
    'WaitTime' => 30, // OPTIONAL, not used yet
    //'Token' => 'auth token', // OPTIONAL
    'TokenInHeader' => true, // OPTIONAL
    'InsecureSkipVerify' => true, // OPTIONAL
]);

$consul = new \DCarbone\PHPConsulAPI\Consul($config);

$kv = $consul->KV;

list($kvp, $qm, $err) = $consul->KV->get('user/marky/cassandra/instance1/username');
if (null !== $err)
    die($err);

var_dump($qm, $kvp);
?>`

**Comment by dcarbone** [comment]
Apologies, in the middle of writing in a new branch and my brain had an old-person moment.

If you've used composer to install it, you should be able to do this:

```php
<?php

require __DIR__ . '/Composer/vendor/autoload.php';

/* Config */
$config = new \DCarbone\PHPConsulAPI\Config([
    'HttpClient' => new GuzzleHttp\Client(),
    'Address' => 'consul.service.blabla.com:8500',
    'Scheme' => 'http',
    'TokenInHeader' => true,
    'InsecureSkipVerify' => true,
]);

$consul = new \DCarbone\PHPConsulAPI\Consul($config);

$kv = $consul->KV;

list($kvp, $qm, $err) = $consul->KV->get('user/marky/cassandra/instance1/username');
if (null !== $err)
    die($err);

var_dump($qm, $kvp);
?>
```

**Comment by dcarbone** [comment]
@anissa747 let me know if that worked for you!

**Comment by anissa747** [comment]
Sorry, I said you tomorrow.

**Comment by anissa747** [comment]
Hello,
How to add a proxy ? 
Because I have to pass by a proxy to access consul.

Thank you

**Comment by dcarbone** [comment]
To utilize a proxy you will have to construct your own client with a proxy path configured.

See the [Guzzle Documentation](http://docs.guzzlephp.org/en/latest/request-options.html#proxy) for more information on the possible structure of the `proxy` key.

Modifying the above code, you should be able to do something like this:

```php
<?php

require __DIR__ . '/Composer/vendor/autoload.php';

/* Config */
$config = new \DCarbone\PHPConsulAPI\Config([
    'HttpClient' => new GuzzleHttp\Client(['proxy' => 'tcp://myproxy.com']),
    'Address' => 'consul.service.blabla.com:8500',
    'Scheme' => 'http',
    'TokenInHeader' => true,
    'InsecureSkipVerify' => true,
]);

$consul = new \DCarbone\PHPConsulAPI\Consul($config);

list($kvp, $qm, $err) = $consul->KV->get('user/marky/cassandra/instance1/username');
if (null !== $err)
    die($err);

var_dump($qm, $kvp);
?>
```

The important piece is this:
```php
'HttpClient' => new GuzzleHttp\Client(['proxy' => 'tcp://myproxy.com']),
```

**Comment by dcarbone** [comment]
In addition, I released a new version yesterday with better support for the new Guzzle-specific implementation.  Please run `composer update` to get the latest version.

**Comment by anissa747** [comment]
I have this error : "500: Internal Server Error".
I don't understand.

**Comment by dcarbone** [comment]
@anissa747 a `500` indicates there is something wrong with your Consul server configuration, or possibly with your proxy.  

I would speak with whomever configured the Consul and Proxy you're attempting to connect to and see if they can dig through logs to find out what might have happened.

**Comment by dcarbone** [comment]
I am going to close this issue, as it does not appear to be the result of an issue with this library.

I will continue to help how I can, however it seems as though this is now an issue you should bring up with your system's administrator.
